#!/bin/sh

checkip() {
    if echo $1 | egrep -q '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' ; then
        a=`echo $1 | awk -F. '{print $1}'`
        b=`echo $1 | awk -F. '{print $2}'`
        c=`echo $1 | awk -F. '{print $3}'`
        d=`echo $1 | awk -F. '{print $4}'`

        for n in $a $b $c $d; do
            if [ $n -ge 255 ] || [ $n -le 0 ]; then
#              echo 'bad ip(2)!'
                return 2
            fi
        done
#       echo 'Ok! You put ip is :' $1
        return 0
    else
 #       echo 'bad ip(1)!'
        return 1
    fi
}

echo   "Input Compus Network's IP:"
read ip
while ( ! (checkip $ip) )
do
   echo   "Error ip, Input Legal Compus Network' Ip:"
   read ip
done

 echo   "Input Compus Network's Gateway:"
read gateway
while ( ! (checkip $gateway) )
do
    echo   "Error ip, Input Legal Gateway:"
   read gateway
done
#echo "OK! You put ip is:$ip"

sleep 1
release=`lsb_release -c | cut  -f2`
echo  "Your release is :	$release"
sleep 1


sleep 1
net_dev=`ifconfig |head -1 | awk '{print $1}'`
echo  "Your network interface(网络设备) is :	$net_dev"
sleep 1


#echo change the execute of static-routes
#chmod +x ./static-routes
echo backup sources.list
sudo cp -p /etc/apt/sources.list /etc/apt/sources.list_backup
sleep 1
echo copy source.list ......
sudo cp -p ./sources.list 	/etc/apt/sources.list
sleep 1
echo copy static-routes ......
sudo cp -p ./static-routes 	/etc/network/if-up.d/static-routes
sleep 1
echo change the execute of static-routes
sudo chmod +x /etc/network/if-up.d/static-routes

sleep 1
echo    "Modify the /etc/network/if-up.d/static-routes"
sed -i -e "s/456.456.456.456/$ip/g"  -e "s/789.789.789.789/$gateway/g" 	/etc/network/if-up.d/static-routes
sed -i -e "s/eth0/$net_dev/g" 	/etc/network/if-up.d/static-routes

sleep 1
echo   "Modify the /etc/apt/sources.list"
sed -i "s/maverick/$release/g" /etc/apt/sources.list
#change the network interface 



#nmcli nm sleep
#sudo ifconfig eth0 down
sudo ifconfig $net_dev down
echo Restarting Network ......
sleep 15
echo Restarting Network ......
#sudo ifconfig eth0 up
sudo ifconfig $net_dev up
sleep 1
#sudo /etc/init.d/networking restart
#nmcli nm wakeup



#while ( [[ `route -n | grep 202.202.0.0|wc -c` -eq 0 ]] && [[ `route -n | grep 172.16.255.255 | wc -c` -eq  0 ]] )
    
#while ( ( `route -n | grep 202.202.0.0|wc -c` == 0 ) && ( `route -n | grep 172.16.255.255 | wc -c` -eq  0 ))
#while ( ( `route -n | grep 202.202.0.0|wc -c` == 0 ) )
#while [ $count -eq 0 ]
#while [  ! "route -n | grep 202.202.0.0" ]

count=`route -n | grep 202.202.0.0|wc -c`
while [ $count -eq 0 ]
do
	echo Adding the route 
	sleep 1
    	count=`route -n | grep 202.202.0.0|wc -c`
done
echo Congratulation! Route have added !
sleep 1
echo Now Update the software Source......
sleep 3
sudo apt-get update
echo ***************************************
echo OK!Enjoy it!
echo ***************************************
