#!/bin/sh

DIR=`pwd`

cat >${DIR}/main.tex <<EOF
\documentclass[UTF8,onecolumn]{ctexart}
\title{}
\date{}
\begin{document}
\end{document}
EOF

cat >${DIR}/makefile <<EOF
.PHONY:all
all:
	xelatex main.tex
	bibtex main.aux
	xelatex main.tex
	xelatex main.tex
	evince main.pdf
clean:
	rm -rfv main.aux main.log main.toc main.dvi *~ main.bbl main.blg main.pdf
easy:
	xelatex main.tex
	evince main.pdf
EOF
echo OK
