#!/bin/sh

DIR=`pwd`

echo "#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int main(int argc, char *argv[])
{
    return 0;
}" > ${DIR}/main.c



echo ".PHONY:a.out
a.out:
	cc main.c
clean:
	rm -rfv *~ a.out" > ${DIR}/makefile

echo OK
