#!/bin/bash

./xkin
count=0
while [ 1 > 0 ]
do
	sleep 300
	poff -a > /dev/null 2>&1
	rm -f /etc/ppp/peers/dsl-provider
	sleep 3
	./xkin

	while [ -z "`ifconfig |grep ppp`" ]
	do
	    poff -a > /dev/null 2>&1
	    rm -f /etc/ppp/peers/dsl-provider
	    sleep 5
	    echo inside...
	    ./xkin > /dev/null 2>&1
	done
done
exit 0